/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PracticeCivilLitigationIndexRouteImport } from './routes/practice/civil-litigation/index'
import { Route as PracticeCivilLitigationBuilderBuyerDisputesRouteImport } from './routes/practice/civil-litigation/builder-buyer-disputes'
import { Route as PracticeCivilLitigationInsuranceClaimsRouteImport } from './routes/practice/civil-litigation/insurance-claims'
import { Route as PracticeCivilLitigationLandlordTenantRouteImport } from './routes/practice/civil-litigation/landlord-tenant'
import { Route as PracticeCivilLitigationMcdTribunalMattersRouteImport } from './routes/practice/civil-litigation/mcd-tribunal-matters'
import { Route as PracticeCivilLitigationProbateOfWillRouteImport } from './routes/practice/civil-litigation/probate-of-will'
import { Route as PracticeCivilLitigationProbateOfWill5RouteImport } from './routes/practice/civil-litigation/probate-of-will-5'
import { Route as PracticeCivilLitigationPropertyDisputesRouteImport } from './routes/practice/civil-litigation/property-disputes'
import { Route as PracticeCivilLitigationPublicNuisanceLitigationRouteImport } from './routes/practice/civil-litigation/public-nuisance-litigation'
import { Route as PracticeCivilLitigationRecoverySuitsRouteImport } from './routes/practice/civil-litigation/recovery-suits'
import { Route as PracticeCivilLitigationRwaElectionMattersRouteImport } from './routes/practice/civil-litigation/rwa-election-matters'
import { Route as PracticeCriminalMattersIndexRouteImport } from './routes/practice/criminal-matters/index'
import { Route as PracticeCriminalMattersBailAndAnticipatoryRouteImport } from './routes/practice/criminal-matters/bail-and-anticipatory'
import { Route as PracticeCriminalMattersCrimesAgainstWomenRouteImport } from './routes/practice/criminal-matters/crimes-against-women'
import { Route as PracticeMatrimonialMattersIndexRouteImport } from './routes/practice/matrimonial-matters/index'
import { Route as PracticeMatrimonialMattersChildCustodyRouteImport } from './routes/practice/matrimonial-matters/child-custody'
import { Route as PracticeMatrimonialMattersDivorceAndMutualConsentRouteImport } from './routes/practice/matrimonial-matters/divorce-and-mutual-consent'
import { Route as PracticeMatrimonialMattersDomesticViolenceRouteImport } from './routes/practice/matrimonial-matters/domestic-violence'
import { Route as PracticeMatrimonialMattersMaintenanceAndAlimonyRouteImport } from './routes/practice/matrimonial-matters/maintenance-and-alimony'
import { Route as PracticeMatrimonialMattersNullityOfMarriageRouteImport } from './routes/practice/matrimonial-matters/nullity-of-marriage'
import { Route as PracticeMatrimonialMattersRestitutionOfConjugalRightsRouteImport } from './routes/practice/matrimonial-matters/restitution-of-conjugal-rights'
import { Route as PracticePropertyRightsIndexRouteImport } from './routes/practice/property-rights/index'
import { Route as PracticePropertyRightsLandAcquisitionRouteImport } from './routes/practice/property-rights/land-acquisition'
import { Route as PracticePropertyRightsPartitionSuitsRouteImport } from './routes/practice/property-rights/partition-suits'
import { Route as PracticePropertyRightsTenancyAndEvictionRouteImport } from './routes/practice/property-rights/tenancy-and-eviction'
import { Route as PracticePropertyRightsTitleAndOwnershipDisputesRouteImport } from './routes/practice/property-rights/title-and-ownership-disputes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeCivilLitigationIndexRoute =
  PracticeCivilLitigationIndexRouteImport.update({
    id: '/practice/civil-litigation/',
    path: '/practice/civil-litigation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCivilLitigationBuilderBuyerDisputesRoute =
  PracticeCivilLitigationBuilderBuyerDisputesRouteImport.update({
    id: '/practice/civil-litigation/builder-buyer-disputes',
    path: '/practice/civil-litigation/builder-buyer-disputes',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCivilLitigationInsuranceClaimsRoute =
  PracticeCivilLitigationInsuranceClaimsRouteImport.update({
    id: '/practice/civil-litigation/insurance-claims',
    path: '/practice/civil-litigation/insurance-claims',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCivilLitigationLandlordTenantRoute =
  PracticeCivilLitigationLandlordTenantRouteImport.update({
    id: '/practice/civil-litigation/landlord-tenant',
    path: '/practice/civil-litigation/landlord-tenant',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCivilLitigationMcdTribunalMattersRoute =
  PracticeCivilLitigationMcdTribunalMattersRouteImport.update({
    id: '/practice/civil-litigation/mcd-tribunal-matters',
    path: '/practice/civil-litigation/mcd-tribunal-matters',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCivilLitigationProbateOfWillRoute =
  PracticeCivilLitigationProbateOfWillRouteImport.update({
    id: '/practice/civil-litigation/probate-of-will',
    path: '/practice/civil-litigation/probate-of-will',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCivilLitigationProbateOfWill5Route =
  PracticeCivilLitigationProbateOfWill5RouteImport.update({
    id: '/practice/civil-litigation/probate-of-will-5',
    path: '/practice/civil-litigation/probate-of-will-5',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCivilLitigationPropertyDisputesRoute =
  PracticeCivilLitigationPropertyDisputesRouteImport.update({
    id: '/practice/civil-litigation/property-disputes',
    path: '/practice/civil-litigation/property-disputes',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCivilLitigationPublicNuisanceLitigationRoute =
  PracticeCivilLitigationPublicNuisanceLitigationRouteImport.update({
    id: '/practice/civil-litigation/public-nuisance-litigation',
    path: '/practice/civil-litigation/public-nuisance-litigation',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCivilLitigationRecoverySuitsRoute =
  PracticeCivilLitigationRecoverySuitsRouteImport.update({
    id: '/practice/civil-litigation/recovery-suits',
    path: '/practice/civil-litigation/recovery-suits',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCivilLitigationRwaElectionMattersRoute =
  PracticeCivilLitigationRwaElectionMattersRouteImport.update({
    id: '/practice/civil-litigation/rwa-election-matters',
    path: '/practice/civil-litigation/rwa-election-matters',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCriminalMattersIndexRoute =
  PracticeCriminalMattersIndexRouteImport.update({
    id: '/practice/criminal-matters/',
    path: '/practice/criminal-matters/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCriminalMattersBailAndAnticipatoryRoute =
  PracticeCriminalMattersBailAndAnticipatoryRouteImport.update({
    id: '/practice/criminal-matters/bail-and-anticipatory',
    path: '/practice/criminal-matters/bail-and-anticipatory',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeCriminalMattersCrimesAgainstWomenRoute =
  PracticeCriminalMattersCrimesAgainstWomenRouteImport.update({
    id: '/practice/criminal-matters/crimes-against-women',
    path: '/practice/criminal-matters/crimes-against-women',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeMatrimonialMattersIndexRoute =
  PracticeMatrimonialMattersIndexRouteImport.update({
    id: '/practice/matrimonial-matters/',
    path: '/practice/matrimonial-matters/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeMatrimonialMattersChildCustodyRoute =
  PracticeMatrimonialMattersChildCustodyRouteImport.update({
    id: '/practice/matrimonial-matters/child-custody',
    path: '/practice/matrimonial-matters/child-custody',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeMatrimonialMattersDivorceAndMutualConsentRoute =
  PracticeMatrimonialMattersDivorceAndMutualConsentRouteImport.update({
    id: '/practice/matrimonial-matters/divorce-and-mutual-consent',
    path: '/practice/matrimonial-matters/divorce-and-mutual-consent',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeMatrimonialMattersDomesticViolenceRoute =
  PracticeMatrimonialMattersDomesticViolenceRouteImport.update({
    id: '/practice/matrimonial-matters/domestic-violence',
    path: '/practice/matrimonial-matters/domestic-violence',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeMatrimonialMattersMaintenanceAndAlimonyRoute =
  PracticeMatrimonialMattersMaintenanceAndAlimonyRouteImport.update({
    id: '/practice/matrimonial-matters/maintenance-and-alimony',
    path: '/practice/matrimonial-matters/maintenance-and-alimony',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeMatrimonialMattersNullityOfMarriageRoute =
  PracticeMatrimonialMattersNullityOfMarriageRouteImport.update({
    id: '/practice/matrimonial-matters/nullity-of-marriage',
    path: '/practice/matrimonial-matters/nullity-of-marriage',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticeMatrimonialMattersRestitutionOfConjugalRightsRoute =
  PracticeMatrimonialMattersRestitutionOfConjugalRightsRouteImport.update({
    id: '/practice/matrimonial-matters/restitution-of-conjugal-rights',
    path: '/practice/matrimonial-matters/restitution-of-conjugal-rights',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticePropertyRightsIndexRoute =
  PracticePropertyRightsIndexRouteImport.update({
    id: '/practice/property-rights/',
    path: '/practice/property-rights/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticePropertyRightsLandAcquisitionRoute =
  PracticePropertyRightsLandAcquisitionRouteImport.update({
    id: '/practice/property-rights/land-acquisition',
    path: '/practice/property-rights/land-acquisition',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticePropertyRightsPartitionSuitsRoute =
  PracticePropertyRightsPartitionSuitsRouteImport.update({
    id: '/practice/property-rights/partition-suits',
    path: '/practice/property-rights/partition-suits',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticePropertyRightsTenancyAndEvictionRoute =
  PracticePropertyRightsTenancyAndEvictionRouteImport.update({
    id: '/practice/property-rights/tenancy-and-eviction',
    path: '/practice/property-rights/tenancy-and-eviction',
    getParentRoute: () => rootRouteImport,
  } as any)
const PracticePropertyRightsTitleAndOwnershipDisputesRoute =
  PracticePropertyRightsTitleAndOwnershipDisputesRouteImport.update({
    id: '/practice/property-rights/title-and-ownership-disputes',
    path: '/practice/property-rights/title-and-ownership-disputes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/practice/civil-litigation/builder-buyer-disputes': typeof PracticeCivilLitigationBuilderBuyerDisputesRoute
  '/practice/civil-litigation/insurance-claims': typeof PracticeCivilLitigationInsuranceClaimsRoute
  '/practice/civil-litigation/landlord-tenant': typeof PracticeCivilLitigationLandlordTenantRoute
  '/practice/civil-litigation/mcd-tribunal-matters': typeof PracticeCivilLitigationMcdTribunalMattersRoute
  '/practice/civil-litigation/probate-of-will': typeof PracticeCivilLitigationProbateOfWillRoute
  '/practice/civil-litigation/probate-of-will-5': typeof PracticeCivilLitigationProbateOfWill5Route
  '/practice/civil-litigation/property-disputes': typeof PracticeCivilLitigationPropertyDisputesRoute
  '/practice/civil-litigation/public-nuisance-litigation': typeof PracticeCivilLitigationPublicNuisanceLitigationRoute
  '/practice/civil-litigation/recovery-suits': typeof PracticeCivilLitigationRecoverySuitsRoute
  '/practice/civil-litigation/rwa-election-matters': typeof PracticeCivilLitigationRwaElectionMattersRoute
  '/practice/criminal-matters/bail-and-anticipatory': typeof PracticeCriminalMattersBailAndAnticipatoryRoute
  '/practice/criminal-matters/crimes-against-women': typeof PracticeCriminalMattersCrimesAgainstWomenRoute
  '/practice/matrimonial-matters/child-custody': typeof PracticeMatrimonialMattersChildCustodyRoute
  '/practice/matrimonial-matters/divorce-and-mutual-consent': typeof PracticeMatrimonialMattersDivorceAndMutualConsentRoute
  '/practice/matrimonial-matters/domestic-violence': typeof PracticeMatrimonialMattersDomesticViolenceRoute
  '/practice/matrimonial-matters/maintenance-and-alimony': typeof PracticeMatrimonialMattersMaintenanceAndAlimonyRoute
  '/practice/matrimonial-matters/nullity-of-marriage': typeof PracticeMatrimonialMattersNullityOfMarriageRoute
  '/practice/matrimonial-matters/restitution-of-conjugal-rights': typeof PracticeMatrimonialMattersRestitutionOfConjugalRightsRoute
  '/practice/property-rights/land-acquisition': typeof PracticePropertyRightsLandAcquisitionRoute
  '/practice/property-rights/partition-suits': typeof PracticePropertyRightsPartitionSuitsRoute
  '/practice/property-rights/tenancy-and-eviction': typeof PracticePropertyRightsTenancyAndEvictionRoute
  '/practice/property-rights/title-and-ownership-disputes': typeof PracticePropertyRightsTitleAndOwnershipDisputesRoute
  '/practice/civil-litigation/': typeof PracticeCivilLitigationIndexRoute
  '/practice/criminal-matters/': typeof PracticeCriminalMattersIndexRoute
  '/practice/matrimonial-matters/': typeof PracticeMatrimonialMattersIndexRoute
  '/practice/property-rights/': typeof PracticePropertyRightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/practice/civil-litigation/builder-buyer-disputes': typeof PracticeCivilLitigationBuilderBuyerDisputesRoute
  '/practice/civil-litigation/insurance-claims': typeof PracticeCivilLitigationInsuranceClaimsRoute
  '/practice/civil-litigation/landlord-tenant': typeof PracticeCivilLitigationLandlordTenantRoute
  '/practice/civil-litigation/mcd-tribunal-matters': typeof PracticeCivilLitigationMcdTribunalMattersRoute
  '/practice/civil-litigation/probate-of-will': typeof PracticeCivilLitigationProbateOfWillRoute
  '/practice/civil-litigation/probate-of-will-5': typeof PracticeCivilLitigationProbateOfWill5Route
  '/practice/civil-litigation/property-disputes': typeof PracticeCivilLitigationPropertyDisputesRoute
  '/practice/civil-litigation/public-nuisance-litigation': typeof PracticeCivilLitigationPublicNuisanceLitigationRoute
  '/practice/civil-litigation/recovery-suits': typeof PracticeCivilLitigationRecoverySuitsRoute
  '/practice/civil-litigation/rwa-election-matters': typeof PracticeCivilLitigationRwaElectionMattersRoute
  '/practice/criminal-matters/bail-and-anticipatory': typeof PracticeCriminalMattersBailAndAnticipatoryRoute
  '/practice/criminal-matters/crimes-against-women': typeof PracticeCriminalMattersCrimesAgainstWomenRoute
  '/practice/matrimonial-matters/child-custody': typeof PracticeMatrimonialMattersChildCustodyRoute
  '/practice/matrimonial-matters/divorce-and-mutual-consent': typeof PracticeMatrimonialMattersDivorceAndMutualConsentRoute
  '/practice/matrimonial-matters/domestic-violence': typeof PracticeMatrimonialMattersDomesticViolenceRoute
  '/practice/matrimonial-matters/maintenance-and-alimony': typeof PracticeMatrimonialMattersMaintenanceAndAlimonyRoute
  '/practice/matrimonial-matters/nullity-of-marriage': typeof PracticeMatrimonialMattersNullityOfMarriageRoute
  '/practice/matrimonial-matters/restitution-of-conjugal-rights': typeof PracticeMatrimonialMattersRestitutionOfConjugalRightsRoute
  '/practice/property-rights/land-acquisition': typeof PracticePropertyRightsLandAcquisitionRoute
  '/practice/property-rights/partition-suits': typeof PracticePropertyRightsPartitionSuitsRoute
  '/practice/property-rights/tenancy-and-eviction': typeof PracticePropertyRightsTenancyAndEvictionRoute
  '/practice/property-rights/title-and-ownership-disputes': typeof PracticePropertyRightsTitleAndOwnershipDisputesRoute
  '/practice/civil-litigation': typeof PracticeCivilLitigationIndexRoute
  '/practice/criminal-matters': typeof PracticeCriminalMattersIndexRoute
  '/practice/matrimonial-matters': typeof PracticeMatrimonialMattersIndexRoute
  '/practice/property-rights': typeof PracticePropertyRightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/practice/civil-litigation/builder-buyer-disputes': typeof PracticeCivilLitigationBuilderBuyerDisputesRoute
  '/practice/civil-litigation/insurance-claims': typeof PracticeCivilLitigationInsuranceClaimsRoute
  '/practice/civil-litigation/landlord-tenant': typeof PracticeCivilLitigationLandlordTenantRoute
  '/practice/civil-litigation/mcd-tribunal-matters': typeof PracticeCivilLitigationMcdTribunalMattersRoute
  '/practice/civil-litigation/probate-of-will': typeof PracticeCivilLitigationProbateOfWillRoute
  '/practice/civil-litigation/probate-of-will-5': typeof PracticeCivilLitigationProbateOfWill5Route
  '/practice/civil-litigation/property-disputes': typeof PracticeCivilLitigationPropertyDisputesRoute
  '/practice/civil-litigation/public-nuisance-litigation': typeof PracticeCivilLitigationPublicNuisanceLitigationRoute
  '/practice/civil-litigation/recovery-suits': typeof PracticeCivilLitigationRecoverySuitsRoute
  '/practice/civil-litigation/rwa-election-matters': typeof PracticeCivilLitigationRwaElectionMattersRoute
  '/practice/criminal-matters/bail-and-anticipatory': typeof PracticeCriminalMattersBailAndAnticipatoryRoute
  '/practice/criminal-matters/crimes-against-women': typeof PracticeCriminalMattersCrimesAgainstWomenRoute
  '/practice/matrimonial-matters/child-custody': typeof PracticeMatrimonialMattersChildCustodyRoute
  '/practice/matrimonial-matters/divorce-and-mutual-consent': typeof PracticeMatrimonialMattersDivorceAndMutualConsentRoute
  '/practice/matrimonial-matters/domestic-violence': typeof PracticeMatrimonialMattersDomesticViolenceRoute
  '/practice/matrimonial-matters/maintenance-and-alimony': typeof PracticeMatrimonialMattersMaintenanceAndAlimonyRoute
  '/practice/matrimonial-matters/nullity-of-marriage': typeof PracticeMatrimonialMattersNullityOfMarriageRoute
  '/practice/matrimonial-matters/restitution-of-conjugal-rights': typeof PracticeMatrimonialMattersRestitutionOfConjugalRightsRoute
  '/practice/property-rights/land-acquisition': typeof PracticePropertyRightsLandAcquisitionRoute
  '/practice/property-rights/partition-suits': typeof PracticePropertyRightsPartitionSuitsRoute
  '/practice/property-rights/tenancy-and-eviction': typeof PracticePropertyRightsTenancyAndEvictionRoute
  '/practice/property-rights/title-and-ownership-disputes': typeof PracticePropertyRightsTitleAndOwnershipDisputesRoute
  '/practice/civil-litigation/': typeof PracticeCivilLitigationIndexRoute
  '/practice/criminal-matters/': typeof PracticeCriminalMattersIndexRoute
  '/practice/matrimonial-matters/': typeof PracticeMatrimonialMattersIndexRoute
  '/practice/property-rights/': typeof PracticePropertyRightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/practice/civil-litigation/builder-buyer-disputes'
    | '/practice/civil-litigation/insurance-claims'
    | '/practice/civil-litigation/landlord-tenant'
    | '/practice/civil-litigation/mcd-tribunal-matters'
    | '/practice/civil-litigation/probate-of-will'
    | '/practice/civil-litigation/probate-of-will-5'
    | '/practice/civil-litigation/property-disputes'
    | '/practice/civil-litigation/public-nuisance-litigation'
    | '/practice/civil-litigation/recovery-suits'
    | '/practice/civil-litigation/rwa-election-matters'
    | '/practice/criminal-matters/bail-and-anticipatory'
    | '/practice/criminal-matters/crimes-against-women'
    | '/practice/matrimonial-matters/child-custody'
    | '/practice/matrimonial-matters/divorce-and-mutual-consent'
    | '/practice/matrimonial-matters/domestic-violence'
    | '/practice/matrimonial-matters/maintenance-and-alimony'
    | '/practice/matrimonial-matters/nullity-of-marriage'
    | '/practice/matrimonial-matters/restitution-of-conjugal-rights'
    | '/practice/property-rights/land-acquisition'
    | '/practice/property-rights/partition-suits'
    | '/practice/property-rights/tenancy-and-eviction'
    | '/practice/property-rights/title-and-ownership-disputes'
    | '/practice/civil-litigation/'
    | '/practice/criminal-matters/'
    | '/practice/matrimonial-matters/'
    | '/practice/property-rights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/practice/civil-litigation/builder-buyer-disputes'
    | '/practice/civil-litigation/insurance-claims'
    | '/practice/civil-litigation/landlord-tenant'
    | '/practice/civil-litigation/mcd-tribunal-matters'
    | '/practice/civil-litigation/probate-of-will'
    | '/practice/civil-litigation/probate-of-will-5'
    | '/practice/civil-litigation/property-disputes'
    | '/practice/civil-litigation/public-nuisance-litigation'
    | '/practice/civil-litigation/recovery-suits'
    | '/practice/civil-litigation/rwa-election-matters'
    | '/practice/criminal-matters/bail-and-anticipatory'
    | '/practice/criminal-matters/crimes-against-women'
    | '/practice/matrimonial-matters/child-custody'
    | '/practice/matrimonial-matters/divorce-and-mutual-consent'
    | '/practice/matrimonial-matters/domestic-violence'
    | '/practice/matrimonial-matters/maintenance-and-alimony'
    | '/practice/matrimonial-matters/nullity-of-marriage'
    | '/practice/matrimonial-matters/restitution-of-conjugal-rights'
    | '/practice/property-rights/land-acquisition'
    | '/practice/property-rights/partition-suits'
    | '/practice/property-rights/tenancy-and-eviction'
    | '/practice/property-rights/title-and-ownership-disputes'
    | '/practice/civil-litigation'
    | '/practice/criminal-matters'
    | '/practice/matrimonial-matters'
    | '/practice/property-rights'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/practice/civil-litigation/builder-buyer-disputes'
    | '/practice/civil-litigation/insurance-claims'
    | '/practice/civil-litigation/landlord-tenant'
    | '/practice/civil-litigation/mcd-tribunal-matters'
    | '/practice/civil-litigation/probate-of-will'
    | '/practice/civil-litigation/probate-of-will-5'
    | '/practice/civil-litigation/property-disputes'
    | '/practice/civil-litigation/public-nuisance-litigation'
    | '/practice/civil-litigation/recovery-suits'
    | '/practice/civil-litigation/rwa-election-matters'
    | '/practice/criminal-matters/bail-and-anticipatory'
    | '/practice/criminal-matters/crimes-against-women'
    | '/practice/matrimonial-matters/child-custody'
    | '/practice/matrimonial-matters/divorce-and-mutual-consent'
    | '/practice/matrimonial-matters/domestic-violence'
    | '/practice/matrimonial-matters/maintenance-and-alimony'
    | '/practice/matrimonial-matters/nullity-of-marriage'
    | '/practice/matrimonial-matters/restitution-of-conjugal-rights'
    | '/practice/property-rights/land-acquisition'
    | '/practice/property-rights/partition-suits'
    | '/practice/property-rights/tenancy-and-eviction'
    | '/practice/property-rights/title-and-ownership-disputes'
    | '/practice/civil-litigation/'
    | '/practice/criminal-matters/'
    | '/practice/matrimonial-matters/'
    | '/practice/property-rights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PracticeCivilLitigationBuilderBuyerDisputesRoute: typeof PracticeCivilLitigationBuilderBuyerDisputesRoute
  PracticeCivilLitigationInsuranceClaimsRoute: typeof PracticeCivilLitigationInsuranceClaimsRoute
  PracticeCivilLitigationLandlordTenantRoute: typeof PracticeCivilLitigationLandlordTenantRoute
  PracticeCivilLitigationMcdTribunalMattersRoute: typeof PracticeCivilLitigationMcdTribunalMattersRoute
  PracticeCivilLitigationProbateOfWillRoute: typeof PracticeCivilLitigationProbateOfWillRoute
  PracticeCivilLitigationProbateOfWill5Route: typeof PracticeCivilLitigationProbateOfWill5Route
  PracticeCivilLitigationPropertyDisputesRoute: typeof PracticeCivilLitigationPropertyDisputesRoute
  PracticeCivilLitigationPublicNuisanceLitigationRoute: typeof PracticeCivilLitigationPublicNuisanceLitigationRoute
  PracticeCivilLitigationRecoverySuitsRoute: typeof PracticeCivilLitigationRecoverySuitsRoute
  PracticeCivilLitigationRwaElectionMattersRoute: typeof PracticeCivilLitigationRwaElectionMattersRoute
  PracticeCriminalMattersBailAndAnticipatoryRoute: typeof PracticeCriminalMattersBailAndAnticipatoryRoute
  PracticeCriminalMattersCrimesAgainstWomenRoute: typeof PracticeCriminalMattersCrimesAgainstWomenRoute
  PracticeMatrimonialMattersChildCustodyRoute: typeof PracticeMatrimonialMattersChildCustodyRoute
  PracticeMatrimonialMattersDivorceAndMutualConsentRoute: typeof PracticeMatrimonialMattersDivorceAndMutualConsentRoute
  PracticeMatrimonialMattersDomesticViolenceRoute: typeof PracticeMatrimonialMattersDomesticViolenceRoute
  PracticeMatrimonialMattersMaintenanceAndAlimonyRoute: typeof PracticeMatrimonialMattersMaintenanceAndAlimonyRoute
  PracticeMatrimonialMattersNullityOfMarriageRoute: typeof PracticeMatrimonialMattersNullityOfMarriageRoute
  PracticeMatrimonialMattersRestitutionOfConjugalRightsRoute: typeof PracticeMatrimonialMattersRestitutionOfConjugalRightsRoute
  PracticePropertyRightsLandAcquisitionRoute: typeof PracticePropertyRightsLandAcquisitionRoute
  PracticePropertyRightsPartitionSuitsRoute: typeof PracticePropertyRightsPartitionSuitsRoute
  PracticePropertyRightsTenancyAndEvictionRoute: typeof PracticePropertyRightsTenancyAndEvictionRoute
  PracticePropertyRightsTitleAndOwnershipDisputesRoute: typeof PracticePropertyRightsTitleAndOwnershipDisputesRoute
  PracticeCivilLitigationIndexRoute: typeof PracticeCivilLitigationIndexRoute
  PracticeCriminalMattersIndexRoute: typeof PracticeCriminalMattersIndexRoute
  PracticeMatrimonialMattersIndexRoute: typeof PracticeMatrimonialMattersIndexRoute
  PracticePropertyRightsIndexRoute: typeof PracticePropertyRightsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/civil-litigation/': {
      id: '/practice/civil-litigation/'
      path: '/practice/civil-litigation'
      fullPath: '/practice/civil-litigation/'
      preLoaderRoute: typeof PracticeCivilLitigationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/civil-litigation/builder-buyer-disputes': {
      id: '/practice/civil-litigation/builder-buyer-disputes'
      path: '/practice/civil-litigation/builder-buyer-disputes'
      fullPath: '/practice/civil-litigation/builder-buyer-disputes'
      preLoaderRoute: typeof PracticeCivilLitigationBuilderBuyerDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/civil-litigation/insurance-claims': {
      id: '/practice/civil-litigation/insurance-claims'
      path: '/practice/civil-litigation/insurance-claims'
      fullPath: '/practice/civil-litigation/insurance-claims'
      preLoaderRoute: typeof PracticeCivilLitigationInsuranceClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/civil-litigation/landlord-tenant': {
      id: '/practice/civil-litigation/landlord-tenant'
      path: '/practice/civil-litigation/landlord-tenant'
      fullPath: '/practice/civil-litigation/landlord-tenant'
      preLoaderRoute: typeof PracticeCivilLitigationLandlordTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/civil-litigation/mcd-tribunal-matters': {
      id: '/practice/civil-litigation/mcd-tribunal-matters'
      path: '/practice/civil-litigation/mcd-tribunal-matters'
      fullPath: '/practice/civil-litigation/mcd-tribunal-matters'
      preLoaderRoute: typeof PracticeCivilLitigationMcdTribunalMattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/civil-litigation/probate-of-will': {
      id: '/practice/civil-litigation/probate-of-will'
      path: '/practice/civil-litigation/probate-of-will'
      fullPath: '/practice/civil-litigation/probate-of-will'
      preLoaderRoute: typeof PracticeCivilLitigationProbateOfWillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/civil-litigation/probate-of-will-5': {
      id: '/practice/civil-litigation/probate-of-will-5'
      path: '/practice/civil-litigation/probate-of-will-5'
      fullPath: '/practice/civil-litigation/probate-of-will-5'
      preLoaderRoute: typeof PracticeCivilLitigationProbateOfWill5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/civil-litigation/property-disputes': {
      id: '/practice/civil-litigation/property-disputes'
      path: '/practice/civil-litigation/property-disputes'
      fullPath: '/practice/civil-litigation/property-disputes'
      preLoaderRoute: typeof PracticeCivilLitigationPropertyDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/civil-litigation/public-nuisance-litigation': {
      id: '/practice/civil-litigation/public-nuisance-litigation'
      path: '/practice/civil-litigation/public-nuisance-litigation'
      fullPath: '/practice/civil-litigation/public-nuisance-litigation'
      preLoaderRoute: typeof PracticeCivilLitigationPublicNuisanceLitigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/civil-litigation/recovery-suits': {
      id: '/practice/civil-litigation/recovery-suits'
      path: '/practice/civil-litigation/recovery-suits'
      fullPath: '/practice/civil-litigation/recovery-suits'
      preLoaderRoute: typeof PracticeCivilLitigationRecoverySuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/civil-litigation/rwa-election-matters': {
      id: '/practice/civil-litigation/rwa-election-matters'
      path: '/practice/civil-litigation/rwa-election-matters'
      fullPath: '/practice/civil-litigation/rwa-election-matters'
      preLoaderRoute: typeof PracticeCivilLitigationRwaElectionMattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/criminal-matters/': {
      id: '/practice/criminal-matters/'
      path: '/practice/criminal-matters'
      fullPath: '/practice/criminal-matters/'
      preLoaderRoute: typeof PracticeCriminalMattersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/criminal-matters/bail-and-anticipatory': {
      id: '/practice/criminal-matters/bail-and-anticipatory'
      path: '/practice/criminal-matters/bail-and-anticipatory'
      fullPath: '/practice/criminal-matters/bail-and-anticipatory'
      preLoaderRoute: typeof PracticeCriminalMattersBailAndAnticipatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/criminal-matters/crimes-against-women': {
      id: '/practice/criminal-matters/crimes-against-women'
      path: '/practice/criminal-matters/crimes-against-women'
      fullPath: '/practice/criminal-matters/crimes-against-women'
      preLoaderRoute: typeof PracticeCriminalMattersCrimesAgainstWomenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/matrimonial-matters/': {
      id: '/practice/matrimonial-matters/'
      path: '/practice/matrimonial-matters'
      fullPath: '/practice/matrimonial-matters/'
      preLoaderRoute: typeof PracticeMatrimonialMattersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/matrimonial-matters/child-custody': {
      id: '/practice/matrimonial-matters/child-custody'
      path: '/practice/matrimonial-matters/child-custody'
      fullPath: '/practice/matrimonial-matters/child-custody'
      preLoaderRoute: typeof PracticeMatrimonialMattersChildCustodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/matrimonial-matters/divorce-and-mutual-consent': {
      id: '/practice/matrimonial-matters/divorce-and-mutual-consent'
      path: '/practice/matrimonial-matters/divorce-and-mutual-consent'
      fullPath: '/practice/matrimonial-matters/divorce-and-mutual-consent'
      preLoaderRoute: typeof PracticeMatrimonialMattersDivorceAndMutualConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/matrimonial-matters/domestic-violence': {
      id: '/practice/matrimonial-matters/domestic-violence'
      path: '/practice/matrimonial-matters/domestic-violence'
      fullPath: '/practice/matrimonial-matters/domestic-violence'
      preLoaderRoute: typeof PracticeMatrimonialMattersDomesticViolenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/matrimonial-matters/maintenance-and-alimony': {
      id: '/practice/matrimonial-matters/maintenance-and-alimony'
      path: '/practice/matrimonial-matters/maintenance-and-alimony'
      fullPath: '/practice/matrimonial-matters/maintenance-and-alimony'
      preLoaderRoute: typeof PracticeMatrimonialMattersMaintenanceAndAlimonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/matrimonial-matters/nullity-of-marriage': {
      id: '/practice/matrimonial-matters/nullity-of-marriage'
      path: '/practice/matrimonial-matters/nullity-of-marriage'
      fullPath: '/practice/matrimonial-matters/nullity-of-marriage'
      preLoaderRoute: typeof PracticeMatrimonialMattersNullityOfMarriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/matrimonial-matters/restitution-of-conjugal-rights': {
      id: '/practice/matrimonial-matters/restitution-of-conjugal-rights'
      path: '/practice/matrimonial-matters/restitution-of-conjugal-rights'
      fullPath: '/practice/matrimonial-matters/restitution-of-conjugal-rights'
      preLoaderRoute: typeof PracticeMatrimonialMattersRestitutionOfConjugalRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/property-rights/': {
      id: '/practice/property-rights/'
      path: '/practice/property-rights'
      fullPath: '/practice/property-rights/'
      preLoaderRoute: typeof PracticePropertyRightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/property-rights/land-acquisition': {
      id: '/practice/property-rights/land-acquisition'
      path: '/practice/property-rights/land-acquisition'
      fullPath: '/practice/property-rights/land-acquisition'
      preLoaderRoute: typeof PracticePropertyRightsLandAcquisitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/property-rights/partition-suits': {
      id: '/practice/property-rights/partition-suits'
      path: '/practice/property-rights/partition-suits'
      fullPath: '/practice/property-rights/partition-suits'
      preLoaderRoute: typeof PracticePropertyRightsPartitionSuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/property-rights/tenancy-and-eviction': {
      id: '/practice/property-rights/tenancy-and-eviction'
      path: '/practice/property-rights/tenancy-and-eviction'
      fullPath: '/practice/property-rights/tenancy-and-eviction'
      preLoaderRoute: typeof PracticePropertyRightsTenancyAndEvictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/property-rights/title-and-ownership-disputes': {
      id: '/practice/property-rights/title-and-ownership-disputes'
      path: '/practice/property-rights/title-and-ownership-disputes'
      fullPath: '/practice/property-rights/title-and-ownership-disputes'
      preLoaderRoute: typeof PracticePropertyRightsTitleAndOwnershipDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PracticeCivilLitigationBuilderBuyerDisputesRoute:
    PracticeCivilLitigationBuilderBuyerDisputesRoute,
  PracticeCivilLitigationInsuranceClaimsRoute:
    PracticeCivilLitigationInsuranceClaimsRoute,
  PracticeCivilLitigationLandlordTenantRoute:
    PracticeCivilLitigationLandlordTenantRoute,
  PracticeCivilLitigationMcdTribunalMattersRoute:
    PracticeCivilLitigationMcdTribunalMattersRoute,
  PracticeCivilLitigationProbateOfWillRoute:
    PracticeCivilLitigationProbateOfWillRoute,
  PracticeCivilLitigationProbateOfWill5Route:
    PracticeCivilLitigationProbateOfWill5Route,
  PracticeCivilLitigationPropertyDisputesRoute:
    PracticeCivilLitigationPropertyDisputesRoute,
  PracticeCivilLitigationPublicNuisanceLitigationRoute:
    PracticeCivilLitigationPublicNuisanceLitigationRoute,
  PracticeCivilLitigationRecoverySuitsRoute:
    PracticeCivilLitigationRecoverySuitsRoute,
  PracticeCivilLitigationRwaElectionMattersRoute:
    PracticeCivilLitigationRwaElectionMattersRoute,
  PracticeCriminalMattersBailAndAnticipatoryRoute:
    PracticeCriminalMattersBailAndAnticipatoryRoute,
  PracticeCriminalMattersCrimesAgainstWomenRoute:
    PracticeCriminalMattersCrimesAgainstWomenRoute,
  PracticeMatrimonialMattersChildCustodyRoute:
    PracticeMatrimonialMattersChildCustodyRoute,
  PracticeMatrimonialMattersDivorceAndMutualConsentRoute:
    PracticeMatrimonialMattersDivorceAndMutualConsentRoute,
  PracticeMatrimonialMattersDomesticViolenceRoute:
    PracticeMatrimonialMattersDomesticViolenceRoute,
  PracticeMatrimonialMattersMaintenanceAndAlimonyRoute:
    PracticeMatrimonialMattersMaintenanceAndAlimonyRoute,
  PracticeMatrimonialMattersNullityOfMarriageRoute:
    PracticeMatrimonialMattersNullityOfMarriageRoute,
  PracticeMatrimonialMattersRestitutionOfConjugalRightsRoute:
    PracticeMatrimonialMattersRestitutionOfConjugalRightsRoute,
  PracticePropertyRightsLandAcquisitionRoute:
    PracticePropertyRightsLandAcquisitionRoute,
  PracticePropertyRightsPartitionSuitsRoute:
    PracticePropertyRightsPartitionSuitsRoute,
  PracticePropertyRightsTenancyAndEvictionRoute:
    PracticePropertyRightsTenancyAndEvictionRoute,
  PracticePropertyRightsTitleAndOwnershipDisputesRoute:
    PracticePropertyRightsTitleAndOwnershipDisputesRoute,
  PracticeCivilLitigationIndexRoute: PracticeCivilLitigationIndexRoute,
  PracticeCriminalMattersIndexRoute: PracticeCriminalMattersIndexRoute,
  PracticeMatrimonialMattersIndexRoute: PracticeMatrimonialMattersIndexRoute,
  PracticePropertyRightsIndexRoute: PracticePropertyRightsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
